services:
  postgres:
    image: postgres:18
    container_name: expense-tracker-practice
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d expense_tracker"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: expense-tracker-app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/expense_tracker
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.xml
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
