services:
  postgres:
    image: postgres:18
    container_name: expense-tracker-practice
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d expense_tracker"]
      interval: 5s
      timeout: 5s
      retries: 10
  mongo:
    image: mongo:7
    container_name: expense-tracker-history-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_history_data:/data/db
  kafka:
    image: apache/kafka:4.0.1
    container_name: expense-tracker-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rabbitmq:
    image: rabbitmq:4-management
    container_name: expense-tracker-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
  app:
    build: .
    container_name: expense-tracker-app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/expense_tracker
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.xml
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: app
      RABBITMQ_PASSWORD: app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      rabbitmq:
        condition: service_started

  history-service:
    build:
      context: .
      dockerfile: Dockerfile.history
    container_name: expense-tracker-history-service
    environment:
      MONGO_URI: mongodb://mongo:27017/expense_history
      MAIN_SERVICE_URL: http://app:8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: app
      RABBITMQ_PASSWORD: app
    ports:
      - "8081:8081"
    depends_on:
      app:
        condition: service_started
      mongo:
        condition: service_started
      kafka:
        condition: service_started
      rabbitmq:
        condition: service_started

volumes:
  postgres_data:
  mongo_history_data:
