FROM eclipse-temurin:21-jdk-alpine-3.22 AS build

WORKDIR /workspace

COPY gradlew settings.gradle build.gradle ./
COPY gradle ./gradle
COPY expense-tracker-greeting-starter ./expense-tracker-greeting-starter
COPY expense-tracker-history-service ./expense-tracker-history-service

RUN chmod +x gradlew
RUN ./gradlew :expense-tracker-history-service:bootJar --no-daemon

FROM eclipse-temurin:21-jre-alpine-3.22

WORKDIR /app

COPY --from=build /workspace/expense-tracker-history-service/build/libs/*.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]
