spring.application.name=expense-tracker-practice

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

management.endpoints.web.exposure.include=health,info,metrics

management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Expense tracker application
info.app.version=0.0.1

filage.greeting.enabled=true
filage.greeting.message=Привет!
filage.greeting.currency=BYN
filage.greeting.date-format=dd.MM.yyyy HH:mm:ss

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:app}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:app}
